//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecoWeb.Domain.Concrete
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RecowebdbEntities : DbContext
    {
        public RecowebdbEntities()
            : base("name=RecowebdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<COW_MenuListByJsonInquiry_Result> COW_MenuListByJsonInquiry()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<COW_MenuListByJsonInquiry_Result>("COW_MenuListByJsonInquiry");
        }
    
        public virtual int PRW_EmployeeSave(string p_EmployeeId, string p_Password, string p_EmployeeName, string p_Email, string p_PhoneNumber, ObjectParameter p_OutMessage)
        {
            var p_EmployeeIdParameter = p_EmployeeId != null ?
                new ObjectParameter("p_EmployeeId", p_EmployeeId) :
                new ObjectParameter("p_EmployeeId", typeof(string));
    
            var p_PasswordParameter = p_Password != null ?
                new ObjectParameter("p_Password", p_Password) :
                new ObjectParameter("p_Password", typeof(string));
    
            var p_EmployeeNameParameter = p_EmployeeName != null ?
                new ObjectParameter("p_EmployeeName", p_EmployeeName) :
                new ObjectParameter("p_EmployeeName", typeof(string));
    
            var p_EmailParameter = p_Email != null ?
                new ObjectParameter("p_Email", p_Email) :
                new ObjectParameter("p_Email", typeof(string));
    
            var p_PhoneNumberParameter = p_PhoneNumber != null ?
                new ObjectParameter("p_PhoneNumber", p_PhoneNumber) :
                new ObjectParameter("p_PhoneNumber", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRW_EmployeeSave", p_EmployeeIdParameter, p_PasswordParameter, p_EmployeeNameParameter, p_EmailParameter, p_PhoneNumberParameter, p_OutMessage);
        }
    
        public virtual ObjectResult<COW_DataStackInquiry_Result> COW_DataStackInquiry(string p_StackCode)
        {
            var p_StackCodeParameter = p_StackCode != null ?
                new ObjectParameter("p_StackCode", p_StackCode) :
                new ObjectParameter("p_StackCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<COW_DataStackInquiry_Result>("COW_DataStackInquiry", p_StackCodeParameter);
        }
    
        public virtual int COW_AuthenticateInquiry(string p_UserId, string p_Password, ObjectParameter p_OutResult, ObjectParameter p_OutMessage)
        {
            var p_UserIdParameter = p_UserId != null ?
                new ObjectParameter("p_UserId", p_UserId) :
                new ObjectParameter("p_UserId", typeof(string));
    
            var p_PasswordParameter = p_Password != null ?
                new ObjectParameter("p_Password", p_Password) :
                new ObjectParameter("p_Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("COW_AuthenticateInquiry", p_UserIdParameter, p_PasswordParameter, p_OutResult, p_OutMessage);
        }
    
        public virtual ObjectResult<PRW_EmployeeInquiry_Result> PRW_EmployeeInquiry(string p_PlantId)
        {
            var p_PlantIdParameter = p_PlantId != null ?
                new ObjectParameter("p_PlantId", p_PlantId) :
                new ObjectParameter("p_PlantId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PRW_EmployeeInquiry_Result>("PRW_EmployeeInquiry", p_PlantIdParameter);
        }
    
        public virtual ObjectResult<PRW_PlantInquiry_Result> PRW_PlantInquiry()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<PRW_PlantInquiry_Result>("PRW_PlantInquiry");
        }
    }
}
